name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.7

      - name: Build and Test
        run: |
          mkdir -p TestLogs
          swift build
          swift test > TestLogs/test-results-$(date +'%Y%m%d-%H%M%S').log

      - name: Commit and Push Logs
        run: |
          if ! gh auth status; then
            echo "GitHub CLI not authenticated. Please authenticate using 'gh auth login'." && exit 1
          fi
          mkdir -p TestLogs
          gh repo sync
          git add TestLogs/
          git commit -m "Add test logs from CI run"
          gh repo sync
