name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Manually install Swift 6.0.3 if not available in prebuilt images
      - name: Install Swift 6.0.3 Manually
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libicu-dev libpython3-dev libsqlite3-dev libxml2-dev libcurl4-openssl-dev
          wget https://download.swift.org/swift-6.0.3-release/ubuntu2204/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE-ubuntu22.04.tar.gz
          tar xzf swift-6.0.3-RELEASE-ubuntu22.04.tar.gz
          sudo mv swift-6.0.3-RELEASE-ubuntu22.04 /usr/local/swift
          echo 'export PATH=/usr/local/swift/usr/bin:$PATH' >> $HOME/.bashrc
          source $HOME/.bashrc
          swift --version

      # Step 3: Make the build and test script executable
      - name: Make Build Script Executable
        run: chmod +x Scripts/build_and_test.sh

      # Step 4: Run the build and test script
      - name: Run Build and Test
        run: Scripts/build_and_test.sh

      # Step 5: Upload test logs as artifacts for further analysis
      - name: Upload Test Logs
        uses: actions/upload-artifact@v3
        with:
          name: TestLogs
          path: TestLogs/
