name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.7

      - name: Build and Test
        run: |
          if [ ! -f Package.swift ]; then
            echo "Package.swift not found! Exiting..."
            exit 1
          fi
          mkdir -p TestLogs
          swift build
          swift test > TestLogs/test-results-$(date +'%Y%m%d-%H%M%S').log

      - name: Commit and Push Logs with Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add TestLogs/
          git commit -m "Add test logs from CI run [CI Commit]" || echo "No changes to commit"
          git push origin || echo "No changes to push"
