name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.7

      - name: Make Build Script Executable
        run: chmod +x Scripts/build_and_test.sh

      - name: Run Build and Test
        run: Scripts/build_and_test.sh

      - name: Upload Test Logs
        uses: actions/upload-artifact@v3
        with:
          name: TestLogs
          path: TestLogs/
